#!/bin/bash

echo "I'm in: "
echo `pwd`

binfile=sample-and-time.p
cfile=sample-and-time.c
exename=$(basename $cfile .c)

echo "Building .bin file $binfile"

pasm -b $binfile

echo "Building .c file $cfile to make $exename"

echo "(Careful - does your .c load the correct .p / .bin?)"

# gcc -g PRUClock-j2.c -o pruclock-j2 -lpthread -lprussdrv
gcc -g $cfile -o $exename -lprussdrv

echo "Running $exename"

./$exename

